task: h1
model_cfg: {

}
urdf_path: resources/robot/h1/urdf/h1.urdf
simulator: mujoco
mujoco_cfg: {
  sim_duration: 10,
  xml_path: resources/robot/h1/scene.xml,
}
issac_gym_cfg: {
  sim_duration: 10
}

controller: mpc
mpc_cfg: {

}

